import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { FlaskerBrewery } from '../src/sites/flasker-breweries.generated';

// Non-brewery site sections + the 5 breweries handled by the curated BREWERY_RULES.
const DROP = new Set([
  'Імпортне пиво', 'НАБОРИ І КОЛАБИ',
  'Mad Brew', 'Vibrant Pour', 'Copper Head', 'Flasker', 'Hoppy Hog',
]);

// Curated canonical overrides (transliteration / abbreviation / spacing / catalog
// form) where the Flasker display name will not reach the real Untappd brewery.
// Seeded from the #304 catalog reconciliation; extend as enrichment misses surface.
const OVERRIDE: Record<string, string> = {
  'Berryland': 'BERRYLAND', 'Gold Fish': 'GoldFish', 'Heather House': 'Heather House Brewery',
  'KLB': 'Kyiv Local Brewery', 'Markel': 'Markel Brewery', 'Mova': 'MOVA brewing co.',
  'MUZA': 'MUZA BREWING CO', 'ProArt': 'ProArt Brewery', 'REALIST': 'Realist',
  'REBREW': 'Rebrew', 'RED CAT': 'Red Cat', 'Ten Men': 'Ten Men Brewery',
  'The Bad Beaver': 'The Bad Beaver!', 'Underwood': 'Underwood Brewery', 'Volta': 'Volta Brewery',
  'Дідько': 'Дідько Brewery', 'Звір Beer': 'Zvir Beer', 'Оболонь': 'Obolon', 'Правда': 'Pravda',
};

// Extra match forms (spacing variants seen in titles/tags).
const EXTRA_MATCH: Record<string, string[]> = {
  'Gold Fish': ['GoldFish'],
  'Vibrant Pour': ['VibrantPour'], // harmless; Vibrant Pour is dropped, kept for documentation
};

function decodeEntities(s: string): string {
  return s
    .replace(/&#0?39;/g, "'").replace(/&apos;/g, "'").replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
}

export function buildRegistryEntries(rawDisplayNames: string[]): FlaskerBrewery[] {
  const seen = new Set<string>();
  const entries: FlaskerBrewery[] = [];
  for (const raw of rawDisplayNames) {
    const display = decodeEntities(raw);
    if (!display || DROP.has(display)) continue;
    const key = display.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    entries.push({
      match: [display, ...(EXTRA_MATCH[display] ?? [])],
      canonical: OVERRIDE[display] ?? display,
    });
  }
  return entries.sort((a, b) => a.match[0].localeCompare(b.match[0]));
}

function render(entries: FlaskerBrewery[]): string {
  const rows = entries.map((e) =>
    `  { match: [${e.match.map((m) => JSON.stringify(m)).join(', ')}], canonical: ${JSON.stringify(e.canonical)} },`,
  ).join('\n');
  return `// GENERATED by scripts/gen-flasker-breweries.ts — do not edit by hand.
// Source: Flasker brand strip (mb-brand-tile), reconciled against the Untappd
// catalog for canonical forms. Regenerate with: npm run gen-flasker-breweries
export interface FlaskerBrewery {
  /** Display forms as they appear in Flasker titles/tags (case-insensitive match). */
  match: string[];
  /** Brewery emitted to the matcher (canonical Untappd form where known). */
  canonical: string;
}

export const FLASKER_BREWERIES: FlaskerBrewery[] = [
${rows}
];
`;
}

async function main(): Promise<void> {
  const { chromium } = await import('playwright');
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36' });
    await page.goto('https://flasker.com.ua/', { waitUntil: 'networkidle', timeout: 60_000 });
    await page.waitForSelector('.mb-brand-tile img[alt]', { timeout: 15_000 });
    const names = await page.$$eval('.mb-brand-tile img[alt]', (imgs) =>
      imgs.map((img) => (img as HTMLImageElement).getAttribute('alt') ?? ''));
    const entries = buildRegistryEntries(names);
    const outPath = fileURLToPath(new URL('../src/sites/flasker-breweries.generated.ts', import.meta.url));
    writeFileSync(outPath, render(entries), 'utf8');
    console.log(`Wrote ${entries.length} breweries to src/sites/flasker-breweries.generated.ts`);
  } finally {
    await browser.close();
  }
}

// Run only when invoked directly, not when imported by the test.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
