// GENERATED by scripts/gen-flasker-breweries.ts — do not edit by hand.
// Source: Flasker brand strip (mb-brand-tile), reconciled against the Untappd
// catalog for canonical forms. Regenerate with: npm run gen-flasker-breweries
export interface FlaskerBrewery {
  /** Display forms as they appear in Flasker titles/tags (case-insensitive match). */
  match: string[];
  /** Brewery emitted to the matcher (canonical Untappd form where known). */
  canonical: string;
}

export const FLASKER_BREWERIES: FlaskerBrewery[] = [
  { match: ["Bench Cafe Brewing"], canonical: "Bench Cafe Brewing" },
  { match: ["Berryland"], canonical: "BERRYLAND" },
  { match: ["Bobr Brew"], canonical: "Bobr Brew" },
  { match: ["BrewArt"], canonical: "BrewArt" },
  { match: ["Burgomistr"], canonical: "Burgomistr" },
  { match: ["CITADEL"], canonical: "CITADEL" },
  { match: ["Comma Brew"], canonical: "Comma Brew" },
  { match: ["D.Kit Family Brewery"], canonical: "D.Kit Family Brewery" },
  { match: ["Diysno Brewery"], canonical: "Diysno Brewery" },
  { match: ["DUMA"], canonical: "DUMA" },
  { match: ["Efir Brewery"], canonical: "Efir Brewery" },
  { match: ["First Actors Brewery"], canonical: "First Actors Brewery" },
  { match: ["Gold Fish", "GoldFish"], canonical: "GoldFish" },
  { match: ["Heather House"], canonical: "Heather House Brewery" },
  { match: ["Holy Brewery"], canonical: "Holy Brewery" },
  { match: ["HREW BREW"], canonical: "HREW BREW" },
  { match: ["IIIO"], canonical: "IIIO" },
  { match: ["KLB"], canonical: "Kyiv Local Brewery" },
  { match: ["Kumpel"], canonical: "Kumpel" },
  { match: ["Lake 62 Brewing"], canonical: "Lake 62 Brewing" },
  { match: ["Malle"], canonical: "Malle" },
  { match: ["Markel"], canonical: "Markel Brewery" },
  { match: ["Mova"], canonical: "MOVA brewing co." },
  { match: ["MUZA"], canonical: "MUZA BREWING CO" },
  { match: ["Pastry Mastery"], canonical: "Pastry Mastery" },
  { match: ["Philosopher"], canonical: "Philosopher" },
  { match: ["pHormula"], canonical: "pHormula" },
  { match: ["ProArt"], canonical: "ProArt Brewery" },
  { match: ["REALIST"], canonical: "Realist" },
  { match: ["REBREW"], canonical: "Rebrew" },
  { match: ["RED CAT"], canonical: "Red Cat" },
  { match: ["Strange Toys"], canonical: "Strange Toys" },
  { match: ["Ten Men"], canonical: "Ten Men Brewery" },
  { match: ["Teréna Térena"], canonical: "Teréna Térena" },
  { match: ["The Bad Beaver"], canonical: "The Bad Beaver!" },
  { match: ["THE WORST BREWERY IN THE WORLD"], canonical: "THE WORST BREWERY IN THE WORLD" },
  { match: ["Underwood"], canonical: "Underwood Brewery" },
  { match: ["Volta"], canonical: "Volta Brewery" },
  { match: ["Блукач"], canonical: "Блукач" },
  { match: ["Гонір"], canonical: "Гонір" },
  { match: ["Дідько"], canonical: "Дідько Brewery" },
  { match: ["Дрофа"], canonical: "Дрофа" },
  { match: ["Звір Beer"], canonical: "Zvir Beer" },
  { match: ["Оболонь"], canonical: "Obolon" },
  { match: ["П'Ю ПЕРШИЙ"], canonical: "П'Ю ПЕРШИЙ" },
  { match: ["Правда"], canonical: "Pravda" },
  { match: ["Хмільний кіт"], canonical: "Хмільний кіт" },
  { match: ["Ципа"], canonical: "Ципа" },
  { match: ["Ягер"], canonical: "Ягер" },
];
